### ISSUE TITLE
Next steps priorities - thoughts

### ISSUE THREAD

**Issue by stevedodson** [elastic/eland#118]
Here are some features that have been discussed as priorities. Please raise more:

1. Setting DateTimeIndex and then filtering and plotting DataFrame with x-axis as time (potentially smart sampling of data for large datasets). E.g.
```
ed_df = ed.DataFrame('localhost', 'flights')
ed_df.set_index('timestamp', inplace=True)
ed_df['2018-01-01':'2018-01-11'].plot()
```
![image](https://user-images.githubusercontent.com/7405463/73278171-1b529500-41e3-11ea-8876-2120a91e81eb.png)

2. Implementing `DataFrame.groupby` and calling ES transform as required:

```
>>> df
   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0
>>> df.groupby(['Animal']).mean()
        Max Speed
Animal
Falcon      375.0
Parrot       25.0
```

3. Transforming a DataFrame field inside a DataFrame e.g.

`ed_df['total_price'] = ed_df['total_price']*10`

4. Running ML jobs from eland (anomaly detection + DFA)

**Comment by tveasey** [comment]
5. I think we should implement the sampling functionality Elasticsearch side, but I would like to have various sampling APIs implemented so one can quickly iterate on representative samples of a large data set.

**Comment by stevedodson** [comment]
6. Add 'dry_run' debug method. i.e. any eland  method that queries ES, could have a 'dry_run' option that would print the ES queries that would be run. This would be very useful for debugging.

**Comment by sethmlarson** [comment]
Some ideas I had:

- Can we remove `eland.Client()` in favor of `elasticsearch.Client()`, seems like a thin wrapper and I'm unsure about the problem it's solving.

- Standardize a "namespace" for functions / parameters related to ES with `es_` as a prefix?
  (use `es_client` everywhere instead of `client`, change `info_es()` to `es_info()`?
  Less worry about future 

- When Eland goes to create an index can we create the index with options that make it friendlier to pandas data types like `NaN` or `NA`? `NA` is already being converted to `null` in ES client, should `NaN` also be this way? Maybe an option?

- Change `._to_pandas()` to `.to_pandas()`, document that the data is loaded into memory and that this should be avoided unless you know what you're doing / require a method not available in Eland.
  Moving this to public signals that this behavior isn't "bad", has it's use-cases.

- `read_csv()` and `read_es()` don't have the same mental diagram of where your data is coming from / going. I know there's a precedent for `read_X()` in pandas/ETL Python libraries, maybe `csv_to_eland()` and `es_to_eland()` provide a better picture?

**Comment by sethmlarson** [comment]
I think all the feature suggestions in this issue have been either implemented or captured elsewhere. Going to close this as it's easier to deal with individual feature suggestions per issue.
