### ISSUE TITLE
The document id ( _id) becomes part of the @timestamp column 

### ISSUE THREAD

**Issue by nl19856** [elastic/eland#268]
I have loaded airbnb data in Elastic

After filling the eland dataframe with: 
`df = ed.read_es(es,'airbnb')`

`df.keys()`
`Index(['@timestamp', 'comments', 'date', 'id', 'listing_id', 'reviewer_id','reviewer_name'], dtype='object')`

When selecting @timestamp the _id has become part of it.

```
df['@timestamp']
-9mHJXQBpH7pS1O5-EKr    2015-06-16 00:00:00+02:00
```

**Comment by stevedodson** [comment]
This is by design. An eland (or pandas) DataFrame has an index. 

In pandas if no index is specified, the index defaults to `RangeIndex if no indexing information part of input data and no index provided.` (https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html).

In eland the index defaults to the elasticsearch `_id` values (https://eland.readthedocs.io/en/latest/reference/api/eland.Index.html).

`df['@timestamp']` is a Series (see pandas.Series/eland.Series) so printing the series will print (index, value) tuples.

**Comment by nl19856** [comment]
OK thanks!
