### ISSUE TITLE
Feature request: join dataframes

### ISSUE THREAD

**Issue by jinserk** [elastic/eland#429]
I am a newbie in eland, but wonder if you have any plan to implement join or merge of two dataframes. Of course I can convert them to pandas, but for a large table, the conversion itself takes too long. It will be the best if we can query with join directly to the elasticsearch.

**Comment by sethmlarson** [comment]
What is the use-case for this? When using Eland typically the data isn't local so "joining" a dataframe would be querying two indices instead of one index. Instead you can pass multiple indices to `eland.DataFrame` to achieve a "joined" dataframe. I'm going to close this as semantically what I'm suggesting I think makes more sense. Using `.join()` would cloud the reality of what you're doing.
