### ISSUE TITLE
`AsyncElasticsearch` support? :)

### ISSUE THREAD

**Issue by igaloly** [elastic/eland#444]
Hey, I see that there's no support for `AsyncElasticsearch`
Will there be? If so, when?

**Comment by sethmlarson** [comment]
I'm not sure if there will be just due to the pandas, numpy, and other computing APIs typically being synchronous. What's your use-case for this?

**Comment by igaloly** [comment]
Our microservices are async.
I want to use this library mainly for fetching complex aggregations from elasticsearch.
This is a use case example: https://www.reddit.com/r/mlops/comments/t9ggiq/alternative_for_implementing_machine_learning/

**Comment by sethmlarson** [comment]
@igaloly Gotcha! Since it's likely this project won't implement async support you should probably go the route of writing these aggregations with [Query DSL](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html) directly. Most of the aggregations in Eland are 1-to-1 mapped to aggregations in Elasticsearch.

Since it's unlikely we'll implement this I'm going to close for now.
